# Generated by Django 5.0.6 on 2024-05-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
