# Generated by Django 5.0.6 on 2024-05-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_category_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount_ends",
        ),
    ]
