# Generated by Django 5.0.6 on 2024-05-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_remove_product_discount_ends"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
