# Generated by Django 5.0.6 on 2024-05-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_product_published"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="store_id",
            new_name="store",
        ),
    ]
