# Generated by Django 5.0.6 on 2024-05-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_productcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="display_order",
            field=models.IntegerField(null=True),
        ),
    ]
