# Generated by Django 5.0.6 on 2024-05-25 09:51

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_alter_gallery_display_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.FileField(upload_to=product.models.product_image_path),
        ),
    ]
