# Generated by Django 5.0.6 on 2024-05-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_productattribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattribute",
            name="value",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
