# Generated by Django 5.0.6 on 2024-05-31 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_order_orderitems"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderItems",
            new_name="OrderItem",
        ),
    ]
