# Generated by Django 5.0.6 on 2024-06-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0015_rename_orderitems_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("approved", "approved"),
                    ("shipped", "shipped"),
                    ("delivered", "delivered"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
