# Generated by Django 5.0.6 on 2024-06-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0017_orderitem_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "processing"),
                    ("accepted", "accepted"),
                    ("shipped", "shipped"),
                    ("delivered", "delivered"),
                ],
                default="processing",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "processing"),
                    ("accepted", "accepted"),
                    ("shipped", "shipped"),
                    ("delivered", "delivered"),
                ],
                default="processing",
                max_length=50,
            ),
        ),
    ]
