# Generated by Django 5.0.6 on 2024-06-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0022_review_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="product",
        ),
        migrations.RemoveField(
            model_name="sell",
            name="price",
        ),
        migrations.RemoveField(
            model_name="sell",
            name="quantity",
        ),
    ]
