# Generated by Django 5.0.6 on 2024-06-12 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0023_remove_review_product_remove_sell_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sell",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sell",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
