# Generated by Django 5.0.6 on 2024-06-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0024_review_product_sell_price_sell_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="product",
        ),
    ]
