# Generated by Django 5.0.6 on 2024-06-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0026_review_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="product",
        ),
    ]
