# Generated by Django 5.0.6 on 2024-06-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0028_productcategory_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
