# Generated by Django 5.0.6 on 2024-05-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="zipcode",
        ),
    ]
