# Generated by Django 5.0.6 on 2024-06-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0003_sell"),
    ]

    operations = [
        migrations.AddField(
            model_name="sell",
            name="orderItem_id",
            field=models.CharField(default="", max_length=255),
        ),
    ]
