# Generated by Django 5.0.6 on 2024-06-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0004_sell_orderitem_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sell",
        ),
    ]
